### ISSUE TITLE
Bugs I found in rom

### ISSUE THREAD

**Issue by Obnomus** [ods-releases/DRG#1]
I don't know If I should ask it here ir not but here are some issue like Screen recording doesn't work no matter what I do, also in apps when I tap on an image to see, it looks likes this

![Screenshot_20241026-092047_Infinity](https://github.com/user-attachments/assets/34a1b1ab-a0a3-49e3-8a26-0f0ddfe19931)

**Comment by npjohnson** [comment]
not how you file bugs - stuff like this exists in the official build as well - report the bug according to the wiki.

**Comment by Obnomus** [comment]
> not how you file bugs - stuff like this exists in the official build as well - report the bug according to the wiki.

I didn't know about wiki, can you share the link for wiki, I'll surely follow it's guide to report a bug

**Comment by npjohnson** [comment]
wiki.lineageos.org
